export const questions = [
	{
		id: "Q1",
		text: "Quelle est la raison de votre présence en gare ?",
		options: [
			{ text: "Je vais prendre le train", next: "Q2" },
			{ text: "Je viens de descendre du train", next: "end" },
			{ text: "J'accompagne des voyageurs qui partent / J'attends des voyageurs qui arrivent", next: "Q2_nv" },
			{ text: "Autre raison (achat billet, commerces en gare...)", next: "Q2_nv" },
		],
	},
	{
		id: "Q2",
		text: "Quelle est l'origine de votre déplacement ? (D'où êtes-vous parti pour arriver à la gare ?)",
		options: [
			{ text: "Lorient", next: "Q2a" },
			{ text: "Autre commune", next: "Q2_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q2_precision",
		text: "Préciser le nom de la commune :",
		freeText: true,
		next: "Q3",
	},
	{
		id: "Q2a",
		text: "De quelle rue de Lorient venez-vous ?",
		freeText: true,
		freeTextPlaceholder: "Nom de la rue",
		next: "Q3",
	},
	{
		id: "Q3",
		text: "Quel mode de transport avez-vous utilisé pour vous rendre à la gare ?",
		options: [
			{ text: "A pied", next: "Q4" },
			{ text: "En voiture -- en tant que conducteur", next: "Q3a" },
			{ text: "En voiture -- en tant que passager", next: "Q3b" },
			{ text: "En bus/car", next: "Q4" },
			{ text: "En bateau-bus", next: "Q4" },
			{ text: "A vélo", next: "Q3d" },
			{ text: "A vélo à assistance électrique (VAE)", next: "Q3d" },
			{ text: "En trottinette", next: "Q3d" },
			{ text: "En Taxi/VTC", next: "Q4" },
			{ text: "En 2 roues Motorisé (Moto, scooter...)", next: "Q3a" },
			{ text: "En train - je fais une correspondance", next: "Q4" },
			{ text: "Autre", next: "Q3_autre", requiresPrecision: true },
		],
	},
	{
		id: "Q3a",
		text: "Où avez-vous stationné votre véhicule ?",
		options: [
			{ text: "Dans le parking Gare Sud au sud de la gare", next: "Q3a1" },
			{ text: "Dans le parking L'orientis au sud de la gare", next: "Q3a1" },
			{ text: "Sur le parking rue Beauvais au nord de la gare", next: "Q3a2" },
			{ text: "Sur une autre place en voirie à durée limitée au nord de la gare", next: "Q3a2" },
			{ text: "Sur une place en voirie non-réglementée au nord de la gare", next: "Q3a2" },
			{ text: "Dans un autre parking public au nord de la gare", next: "Q3a2" },
			{ text: "Sur une autre place en voirie à durée limitée au sud de la gare", next: "Q3a2" },
			{ text: "Sur une place en voirie non-réglementée au sud de la gare", next: "Q3a2" },
			{ text: "Dans un autre parking public au sud de la gare (Nayel, Place d'Armes...)", next: "Q3a2" },
			{ text: "Sur un stationnement privé (box ou place de parking privée)", next: "Q3a2" },
		],
	},
	{
		id: "Q3a1",
		text: "Disposez-vous d'un abonnement ou d'un tarif préférentiel pour le stationnement ?",
		options: [
			{ text: "Oui, j'ai un abonnement 24h/24h", next: "Q3a4" },
			{ text: "Oui, j'ai un abonnement Actif", next: "Q3a4" },
			{ text: "Non, je paye au prorata de ma durée de stationnement (dont forfaits courtes durées)", next: "Q3a4" },
		],
	},
	{
		id: "Q3a2",
		text: "Disposez-vous d'un macaron résident ?",
		options: [
			{ text: "Oui", next: "Q3a3" },
			{ text: "Non", next: "Q3a3" },
		],
	},
	{
		id: "Q3a3",
		text: "Pouvez-vous nous indiquer le nom de la rue ou du parking où vous vous êtes garé ?",
		freeText: true,
		next: "Q3a4",
	},
	{
		id: "Q3a4",
		text: "Combien de temps allez-vous laisser votre voiture stationnée ?",
		options: [
			{ text: "Moins de 2 heures", next: "Q4" },
			{ text: "Une demi-journée (entre 2 et 4 heures)", next: "Q4" },
			{ text: "Une journée entière (entre 4h et 12h)", next: "Q4" },
			{ text: "2 à 3 jours", next: "Q4" },
			{ text: "3 à 6 jours", next: "Q4" },
			{ text: "1 semaine ou plus", next: "Q4" },
		],
	},
	{
		id: "Q3b",
		text: "Où vous êtes-vous fait déposer ?",
		options: [
			{ text: "Au niveau de la dépose-minute devant le bâtiment voyageur au Nord", next: "Q4" },
			{ text: "Au niveau du parking ou de la rue Beauvais au Nord", next: "Q4" },
			{ text: "Au niveau de la dépose-minute devant le parvis au Sud", next: "Q4" },
			{ text: "Autre", next: "Q3b_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q3b_precision",
		text: "Veuillez préciser l'endroit où vous vous êtes fait déposer :",
		freeText: true,
		next: "Q4",
	},
	{
		id: "Q3d",
		text: "Où avez-vous stationné votre vélo/trottinette ?",
		options: [
			{ text: "Sur les arceaux vélos côté nord (rue Beauvais)", next: "Q4" },
			{ text: "En consigne collective sur le parvis nord (rue Beauvais)", next: "Q4" },
			{ text: "Sur les arceaux vélos parvis sud", next: "Q4" },
			{ text: "En consigne collective parvis sud", next: "Q4" },
			{ text: "Je le transporte avec moi dans le train", next: "Q4" },
			{ text: "Autre", next: "Q3d_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q3d_precision",
		text: "Veuillez préciser où vous avez stationné votre vélo/trottinette :",
		freeText: true,
		next: "Q4",
	},
	{
		id: "Q3_autre",
		text: "Précisez le mode de transport utilisé :",
		freeText: true,
		next: "Q4",
	},
	{
		id: "Q4",
		text: "Possédez-vous un abonnement TER ?",
		options: [
			{ text: "Oui", next: "Q5" },
			{ text: "Non", next: "Q5" },
			{ text: "Non mais j'envisage d'en prendre un dans les mois qui viennent", next: "Q5" },
		],
	},
	{
		id: "Q5",
		text: "Pour ce trajet en train, quelle sera votre gare de descente ?",
		freeText: true,
		freeTextPlaceholder: "Nom de la gare",
		next: "Q6",
	},
	{
		id: "Q6",
		text: "Quel est le motif de votre déplacement en train ?",
		options: [
			{ text: "Je me rends sur mon lieu de travail", next: "Q7" },
			{ text: "Je me rends sur mon lieu d'études", next: "Q7" },
			{ text: "Je rentre à mon domicile principal", next: "Q6a" },
			{ text: "Déplacement professionnel", next: "Q7" },
			{ text: "Loisirs, tourisme", next: "Q7" },
			{ text: "(Achats, démarches administratives, RDV médical, visite…)", next: "Q6_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q6_precision",
		text: "Veuillez préciser le motif de votre déplacement :",
		freeText: true,
		next: "Q7",
	},
	{
		id: "Q6a",
		text: "Quel était la raison de votre venue à Lorient ?",
		options: [
			{ text: "Mon lieu de travail se situe à Lorient (ou à proximité)", next: "Q7" },
			{ text: "Mon lieu d'études se situe à Lorient (ou à proximité)", next: "Q7" },
			{ text: "Je suis venu pour un déplacement professionnel", next: "Q7" },
			{ text: "Loisirs, tourisme", next: "Q7" },
			{ text: "Autres", next: "Q7", requiresPrecision: true },
		],
	},
	{
		id: "Q7",
		text: "A quelle fréquence réalisez-vous ce déplacement en train ?",
		options: [
			{ text: "Tous les jours de la semaine ou presque (Plus de 3 fois par semaine)", next: "Q8" },
			{ text: "Régulièrement (au moins une fois par mois)", next: "Q8" },
			{ text: "Occasionnellement (moins d'une fois par mois)", next: "Q8" },
		],
	},
	{
		id: "Q8",
		text: "Quel âge avez-vous ?",
		options: [
			{ text: "Moins de 18 ans", next: "Q9" },
			{ text: "Entre 18 et 30 ans", next: "Q9" },
			{ text: "Entre 30 et 40 ans", next: "Q9" },
			{ text: "Entre 40 et 55 ans", next: "Q9" },
			{ text: "Entre 55 et 65 ans", next: "Q9" },
			{ text: "Plus de 65 ans", next: "Q9" },
		],
	},
	{
		id: "Q9",
		text: "Selon vous, que faudrait-il faire en priorité pour améliorer les conditions d'accès à cette gare ?",
		freeText: true,
		freeTextPlaceholder: "Votre réponse",
		next: "end",
	},
	{
		id: "Q2_nv",
		text: "Quelle est l'origine de votre déplacement ? (D'où êtes-vous parti pour arriver à la gare ?)",
		options: [
			{ text: "Lorient", next: "Q2a_nv" },
			{ text: "Autre commune", next: "Q2_precis_nv", requiresPrecision: true },
		],
	},
	{
		id: "Q2_precis_nv",
		text: "Préciser le nom de la commune :",
		freeText: true,
		next: "Q3_nv",
	},
	{
		id: "Q2a_nv",
		text: "De quelle rue de Lorient venez-vous ?",
		freeText: true,
		freeTextPlaceholder: "Nom de la rue",
		next: "Q3_nv",
	},
	{
		id: "Q3_nv",
		text: "Quel mode de transport avez-vous utilisé pour vous rendre à la gare ?",
		options: [
			{ text: "A pied", next: "Q8_nv" },
			{ text: "En voiture -- en tant que conducteur", next: "Q3a_nv" },
			{ text: "En voiture -- en tant que passager", next: "Q3b_nv" },
			{ text: "En bus/car", next: "Q8_nv" },
			{ text: "En bateau-bus", next: "Q8_nv" },
			{ text: "A vélo", next: "Q3d_nv" },
			{ text: "A vélo à assistance électrique (VAE)", next: "Q3d_nv" },
			{ text: "En trottinette", next: "Q3d_nv" },
			{ text: "En Taxi/VTC", next: "Q8_nv" },
			{ text: "En 2 roues Motorisé (Moto, scooter...)", next: "Q3a_nv" },
			{ text: "En train - je fais une correspondance", next: "Q8_nv" },
			{ text: "Autre", next: "Q3_autre_nv", requiresPrecision: true },
		],
	},
	{
		id: "Q3_autre_nv",
		text: "Précisez le mode de transport utilisé :",
		freeText: true,
		next: "Q8_nv",
	},
	{
		id: "Q3a_nv",
		text: "Où avez-vous stationné votre véhicule ?",
		options: [
			{ text: "Dans le parking Gare Sud au sud de la gare", next: "Q3a1_nv" },
			{ text: "Dans le parking L'orientis au sud de la gare", next: "Q3a1_nv" },
			{ text: "Sur le parking rue Beauvais au nord de la gare", next: "Q3a2_nv" },
			{ text: "Sur une autre place en voirie à durée limitée au nord de la gare", next: "Q3a2_nv" },
			{ text: "Sur une place en voirie non-réglementée au nord de la gare", next: "Q3a2_nv" },
			{ text: "Dans un autre parking public au nord de la gare", next: "Q3a2_nv" },
			{ text: "Sur une place en voirie à durée limitée entée au sud de la gare", next: "Q3a2_nv" },
			{ text: "Sur une place en voirie non-réglementée au sud de la gare", next: "Q3a2_nv" },
			{ text: "Dans un autre parking public au sud de la gare (Nayel, Place d'Armes...)", next: "Q3a2_nv" },
			{ text: "Sur un stationnement privé (box ou place de parking privée)", next: "Q3a2_nv" },
		],
	},
	{
		id: "Q3a1_nv",
		text: "Disposez-vous d’un abonnement pour le stationnement en parking payant ?",
		options: [
			{ text: "Oui, j'ai un abonnement 24h/24h", next: "Q3a4_nv" },
			{ text: "Oui, j'ai un abonnement Actif", next: "Q3a4_nv" },
			{ text: "Non, je paye au prorata de ma durée de stationnement (dont forfaits courtes durées)", next: "Q3a4_nv" },
		],
	},
	{
		id: "Q3a2_nv",
		text: "Disposez-vous d'un macaron résident ?",
		options: [
			{ text: "Oui", next: "Q3a3_nv" },
			{ text: "Non", next: "Q3a3_nv" },
		],
	},
	{
		id: "Q3a3_nv",
		text: "Pouvez-vous nous indiquer le nom de la rue ou du parking où vous vous êtes garé ?",
		freeText: true,
		next: "Q3a4_nv",
	},
	{
		id: "Q3a4_nv",
		text: "Combien de temps allez-vous laisser votre voiture stationnée ?",
		options: [
			{ text: "Moins de 2 heures", next: "Q8_nv" },
			{ text: "Une demi-journée (entre 2 et 4 heures)", next: "Q8_nv" },
			{ text: "Une journée entière (entre 4h et 12h)", next: "Q8_nv" },
			{ text: "2 à 3 jours", next: "Q8_nv" },
			{ text: "3 à 6 jours", next: "Q8_nv" },
			{ text: "1 semaine ou plus", next: "Q8_nv" },
		],
	},
	{
		id: "Q3b_nv",
		text: "Où vous êtes-vous fait déposer ?",
		options: [
			{ text: "Au niveau de la dépose-minute devant le bâtiment voyageur au Nord", next: "Q8_nv" },
			{ text: "Au niveau du parking ou de la rue Beauvais au Nord", next: "Q8_nv" },
			{ text: "Au niveau de la dépose-minute devant le parvis au Sud", next: "Q8_nv" },
			{ text: "Autre", next: "Q3b_precis_nv", requiresPrecision: true },
		],
	},
	{
		id: "Q3b_precis_nv",
		text: "Veuillez préciser l'endroit où vous vous êtes fait déposer :",
		freeText: true,
		next: "Q8_nv",
	},
	{
		id: "Q3d_nv",
		text: "Où avez-vous stationné votre vélo/trottinette ?",
		options: [
			{ text: "Sur les arceaux vélos côté nord (rue Beauvais)", next: "Q8_nv" },
			{ text: "En consigne collective sur le parvis nord (rue Beauvais)", next: "Q8_nv" },
			{ text: "Sur les arceaux vélos parvis sud", next: "Q8_nv" },
			{ text: "En consigne collective parvis sud", next: "Q8_nv" },
			{ text: "Autre", next: "Q3d_precis_nv", requiresPrecision: true },
		],
	},
	{
		id: "Q3d_precis_nv",
		text: "Veuillez préciser où vous avez stationné votre vélo/trottinette :",
		freeText: true,
		next: "Q8_nv",
	},
	{
		id: "Q8_nv",
		text: "Quel âge avez-vous ?",
		options: [
			{ text: "Moins de 18 ans", next: "Q9_nv" },
			{ text: "Entre 18 et 30 ans", next: "Q9_nv" },
			{ text: "Entre 30 et 40 ans", next: "Q9_nv" },
			{ text: "Entre 40 et 55 ans", next: "Q9_nv" },
			{ text: "Entre 55 et 65 ans", next: "Q9_nv" },
			{ text: "Plus de 65 ans", next: "Q9_nv" },
		],
	},
	{
		id: "Q9_nv",
		text: "Selon vous, que faudrait-il faire en priorité pour améliorer les conditions d'accès à cette gare ?",
		freeText: true,
		freeTextPlaceholder: "Votre réponse",
		next: "end",
	},
];